version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    ports:
      - "9090:8080"
    networks:
      - jenkins-sonar-net

  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - jenkins-sonar-net

networks:
  jenkins-sonar-net:
